name: Linter

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_BASH: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_ENV: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_KUBERNETES_KUBECONFORM: true
          VALIDATE_ANSIBLE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSONC_PRETTIER: true
          VALIDATE_JSX_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
